### ISSUE TITLE
opengraph tags are specified as 'name' instead of 'property'

### ISSUE THREAD

**Issue by madhusudanbabar** [AlekseyPleshkov/nuxt-social-meta#5]
The tags currently have the `key` as the name instead of property, the Facebook debugger shows this message: ```The following meta tags are specified using 'name' instead of 'property' and will be ignored unless specified using the 'property' key: og:image, og:locale```

**Comment by madhusudanbabar** [comment]
refer this [link](https://developers.facebook.com/docs/sharing/webmasters#markup)

**Comment by wboka** [comment]
Is this going to be pushed to NPM?

**Comment by AlekseyPleshkov** [comment]
Coming soon

**Comment by bjesus** [comment]
Any news on this? LinkedIn shows our website without an image because of this issue 😕

**Comment by wboka** [comment]
If you don't want to wait you could write your own function from the `index.js` file and import it manually. 

```js
import socialMedia from "~/helpers/social-tags"; // I put mine in a helpers directory and called it social-tags.js

// Code omitted for brevity
const options = {
	url: "",
	title: "",
	site_name: "",
	description: "",
	img: "",
	locale: "",
	twitter: "",
	twitter_card: "",
	themeColor: "",
};

// ...
export default {
	head() {
		return {
			// ...
			meta: socialMedia(options),
                        // ...
		};
	},
},
// ...
```
