### ISSUE TITLE
add width and height

### ISSUE THREAD

**Issue by borisdayma** [AlekseyPleshkov/nuxt-social-meta#8]
It would be nice to be able to add `og:image:width` and `og:image:height` properties

**Comment by AlekseyPleshkov** [comment]
Hello! You should update your package version to 1.0.0 and add parameter `img_size: { width: "Image width in px", height: "Image height in px" },` 👌

**Comment by patrick-ve** [comment]
Do I need to set explicit height and width values inside `img_size`? Whatever I try, I keep getting this error:

![Screenshot 2021-07-11 at 10 50 05](https://user-images.githubusercontent.com/37079247/125188914-ee0e7100-e235-11eb-880f-bbdc61fe6fa8.png)
